sudo: required
language: php

php:
  - 7.2
  - 7.3
  - nightly

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

matrix:
    allow_failures:
        - php: nightly

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.xml
