sudo: required
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

after_failure:
  - tail vendor/orchestra/testbench-dusk/laravel/storage/logs/laravel.log

matrix:
    allow_failures:
        - php: nightly

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.xml
